//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fronius.Library.Services.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Individual
    {
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string FullName_CPT { get; set; }
    
        public virtual Author Author { get; set; }
        public virtual Illustrator Illustrator { get; set; }
    }
}
